name: pulling shit in other shit check

on: pull_request

jobs:
  frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install npm
        run: npm install
        working-directory: frontend
      - name: build
        run: npm run build
        working-directory: frontend

#  christianLindner:
#    name: Christian Lindner
#    runs-on: ubuntu-latest
#
#    steps:
#      - name: Check out repository code
#        uses: actions/checkout@v3
#      - name: Install npm
#        run: npm install
#        working-directory: frontend
#      - name: lint
#        run: npx eslint .
#        working-directory: frontend